apiVersion: v1
kind: Pod
metadata:
  name: vpnserver
  labels:
    app: vpnserver
spec:
  containers:
    - name: traefik
      image: docker.io/traefik:latest
      ports:
        - containerPort: 80
          hostPort: 30080
        - containerPort: 443
          hostPort: 30443
      volumeMounts:
        - name: traefik
          mountPath: /etc/traefik
      tty: true
    - name: certdumper
      image: docker.io/ldez/traefik-certs-dumper:v2.8.1
      command: 
        - "sh"
        - "-c"
        - '
          apk add jq
          ; while ! [ -e /data/acme.json ]
          || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
          sleep 1
          ; done
          && traefik-certs-dumper file --version v2 --watch --source /data/acme.json --dest /output/certdumper --crt-ext=.pem'
      volumeMounts:
        - name: traefik
          mountPath: /data
        - name: x-ui
          mountPath: /output
    - name: x-ui
      image: docker.io/alireza7/x-ui:latest
      env:
        - name: XRAY_VMESS_AEAD_FORCED
          value: false
      ports:
        - containerPort: 60001
          hostPort: 60001
          protocol: TCP
      volumeMounts:
        - name: x-ui
          mountPath: /etc/x-ui
      tty: true
    # - name: wg-easy
    #   image: docker.io/weejewel/wg-easy:latest
    #   env:
    #     - name: WG_HOST
    #       value: petchup.ddns.net
    #   ports:
    #     - containerPort: 51820
    #       hostPort: 60000
    #       protocol: UDP
    #   volumeMounts:
    #     - name: wg-easy
    #       mountPath: /etc/wireguard
    #   securityContext:
    #     capabilities:
    #       add:
    #         - NET_ADMIN
    #         - SYS_MODULE
    #     sysctls:
    #       - name: net.ipv4.ip_forward
    #         value: "1"
    #       - name: net.ipv4.conf.all.src_valid_mark
    #         value: "1"
    #     allowPrivilegeEscalation: false
    #     runAsUser: 0
    #   tty: true
  volumes:
    - name: traefik
      hostPath:
        type: DirectoryOrCreate
        path: /opt/vpn/traefik
    - name: x-ui
      hostPath:
        type: DirectoryOrCreate
        path: /opt/vpn/x-ui
    # - name: wg-easy
    #   hostPath:
    #     type: DirectoryOrCreate
    #     path: /opt/vpn/wg-easy