apiVersion: v1
kind: Pod
metadata:
  name: vpnserver
  labels:
    app: vpnserver
spec:
  containers:
    - name: redirect
      image: docker.io/morbz/docker-web-redirect
      ports:
        - containerPort: 80
          hostPort: 65080
    - name: x-ui
      image: docker.io/alireza7/x-ui:latest
      env:
        - name: XRAY_VMESS_AEAD_FORCED
          value: false
      ports:
        - containerPort: 443
          hostPort: 65443
        - containerPort: 443
          hostPort: 65443
          protocol: UDP
        - containerPort: 54321
          hostPort: 65432
      volumeMounts:
        - name: x-ui
          mountPath: /etc/x-ui
        - name: certs
          mountPath: /certs
  volumes:
    - name: x-ui
      hostPath:
        type: DirectoryOrCreate
        path: /opt/vpn/vps-vpn/x-ui
    - name: certs
      hostPath:
        type: DirectoryOrCreate
        path: /opt/vpn/vps-vpn/certs