apiVersion: v1
kind: Pod
metadata:
  name: vpnserver
  labels:
    app: vpnserver
spec:
  containers:
    - name: x-ui
      image: docker.io/alireza7/x-ui:latest
      env:
        - name: XRAY_VMESS_AEAD_FORCED
          value: false
      ports:
        - containerPort: 443
          hostPort: 443
          protocol: TCP
      volumeMounts:
        - name: x-ui
          mountPath: /etc/x-ui
  volumes:
    - name: x-ui
      hostPath:
        type: DirectoryOrCreate
        path: /opt/vpn/x-ui